version: '3.8'

services:
  # База данных внутри Docker
  postgres:
    image: postgres:14-alpine
    container_name: w2g_postgres
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Монтируем наш единый скрипт инициализации
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Redis внутри Docker
  redis:
    image: redis:7-alpine
    container_name: w2g_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redisdata:/data

  # Бэкенд
  api:
    build: .
    container_name: w2g_backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      # Переопределяем хосты для внутренней сети Docker
      DB_HOST: postgres
      REDIS_HOST: redis
      DB_PORT: 5432
    volumes:
      - ./src:/usr/src/app/src
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
      - /usr/src/app/node_modules
    
    # --- Monitoring: Prometheus ---
  prometheus:
    image: prom/prometheus:latest
    container_name: w2g_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # --- Monitoring: Grafana ---
  grafana:
    image: grafana/grafana:latest
    container_name: w2g_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus
  
    # --- Microservice: Analytics ---
  analytics:
    build: ../W2G_Analytics  # Путь к папке соседнего сервиса
    container_name: w2g_analytics
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  pgdata:
  redisdata:


# Для PostgreSQL:

# # 1. Заходим внутрь контейнера с базой
# docker exec -it w2g_postgres psql -U postgres -d watchparty_db

# Когда увидишь watchparty_db=#, ты внутри!
# Вводи команды:
# \dt — показать список таблиц (ты должен увидеть users, rooms, movies и т.д.).
# SELECT * FROM users; — посмотреть пользователей.
# \q — выход.


#---------------------------------------------------------------------------

# Для Redis:

# # 1. Заходим внутрь Redis
# docker exec -it w2g_redis redis-cli

# # 2. Проверяем ключи
# KEYS *

#---------------------------------------------------------------------------

# Выдать себе Админку 

# docker exec -it w2g_postgres psql -U postgres -d watchparty_db -c "UPDATE users SET role = 'admin' WHERE email = 'admin@gmail.com';"